dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    confinement: classic
    channel: latest/beta
sudo: required
language: csharp
solution: ./CinemaWorld/src/CinemaWorld.sln
mono: none
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet --version
  - dotnet build
  - xbuild /p:Configuration=Release /CinemaWorld/src/CinemaWorld.sln
