dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    confinement: classic
    channel: latest/beta
sudo: required
dotnet: 3.1.202
language: csharp
solution: src/CinemaWorld.sln
mono: none
install:
  - dotnet restore
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet --version
  - dotnet build
