dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    confinement: classic
    channel: latest/beta
sudo: required
dotnet: 3.1.202
language: csharp
solution: /CinemaWorld/src/CinemaWorld.sln
install:
  - cd CinemaWorld
  - dotnet restore /src/CinemaWorld.sln
mono: none
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet --version
  - dotnet build
